### ISSUE TITLE
Useless 

### ISSUE THREAD

**Issue by Sowd0404** [TheGreatSageEqualToHeaven/Beer#2]
Most if not all common script releases uses mostly non executor env functions (Just simple scripts like firing a remote, etc), by making this, the most you are catering to is the autistic bitcoin mining executors which intentionally name functions such as hookfunction to pushclosure and etc. Most of these said executors do not even provide a docs nor do their custom functions usually work as they were probably taken from the 2019 Synapse leak 📦

99.9% of scripts made for Synapse work on Krnl and otherwise you can fix it with very simple checks. 

Considering you shit on everybody else's projects I just came here to lay my asshole opinion on your dog shit idea 
![image](https://user-images.githubusercontent.com/70187756/141656363-abd47911-19f6-4885-b417-7b3b6cf0672d.png)

**Comment by TheGreatSageEqualToHeaven** [comment]
Useless Issue
